import type { PaySnapshot } from "@/lib/storage/pay-store";

export function createPayDemoSnapshot(): PaySnapshot {
  return {
    subscriptions: [
      {
        id: "demo-netflix",
        name: "Netflix",
        amount: 15.49,
        cycle: "monthly",
        category: "streaming",
        startDate: "2022-01",
        renewalDay: 8,
        currency: "USD",
        priceHistory: [
          { amount: 13.99, effectiveMonth: "2022-01" },
          { amount: 15.49, effectiveMonth: "2024-01" },
        ],
        active: true,
      },
      {
        id: "demo-spotify",
        name: "Spotify",
        amount: 10.99,
        cycle: "monthly",
        category: "music",
        startDate: "2021-06",
        renewalDay: 14,
        currency: "USD",
        priceHistory: [
          { amount: 9.99, effectiveMonth: "2021-06" },
          { amount: 10.99, effectiveMonth: "2023-08" },
        ],
        active: true,
      },
      {
        id: "demo-icloud",
        name: "iCloud+",
        amount: 2.99,
        cycle: "monthly",
        category: "cloud",
        startDate: "2023-03",
        renewalDay: 22,
        currency: "USD",
        priceHistory: [{ amount: 2.99, effectiveMonth: "2023-03" }],
        active: true,
      },
      {
        id: "demo-github",
        name: "GitHub Pro",
        amount: 4.0,
        cycle: "monthly",
        category: "software",
        startDate: "2022-09",
        renewalDay: 1,
        currency: "USD",
        priceHistory: [{ amount: 4.0, effectiveMonth: "2022-09" }],
        active: true,
      },
      {
        id: "demo-gym",
        name: "Gym membership",
        amount: 49.99,
        cycle: "monthly",
        category: "fitness",
        startDate: "2023-01",
        renewalDay: 5,
        currency: "USD",
        priceHistory: [
          { amount: 39.99, effectiveMonth: "2023-01" },
          { amount: 44.99, effectiveMonth: "2024-06" },
          { amount: 49.99, effectiveMonth: "2025-01" },
        ],
        active: true,
      },
      {
        id: "demo-amazon",
        name: "Amazon Prime",
        amount: 139.0,
        cycle: "yearly",
        category: "shopping",
        startDate: "2022-04",
        renewalDay: 12,
        currency: "USD",
        priceHistory: [
          { amount: 119.0, effectiveMonth: "2022-04" },
          { amount: 139.0, effectiveMonth: "2023-09" },
        ],
        active: true,
      },
    ],
    currency: "USD",
  };
}
